//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public string Nick { get; set; }
        public string Pass { get; set; }
        public Nullable<System.DateTime> LastActivity { get; set; }
        public string Security_Question { get; set; }
        public string Security_Answer { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    
        public virtual Tank Tank { get; set; }
    }
}
