//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tank
    {
        public int Id { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<System.DateTime> LastGame { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
